version: '3.8'

services:
  database:
    image: postgres:13
    container_name: postgres
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - internal
  
  merch_store:
    build:
      dockerfile: Dockerfile
      context: .
    environment:
      - CONFIG_PATH=./configs/local.yaml
      - SECRET_KEY=test_secret
      - DB_HOST=database
      - DB_PORT=5432
      - DB_SSLMODE=disable
      - POSTGRES_DB=db
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
    ports:
      - 8080:8080
    networks:
      - internal

volumes:
  pg_data:
    
networks:
  internal: