version: '3.8'

services:
  db:
    image: postgres:13
    container_name: postgres
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U postgres -d shop'"]
      interval: 5s
      timeout: 10s
      retries: 5
      start_period: 10s
    networks:
      - internal
  
  merch_store:
    build:
      dockerfile: Dockerfile
      context: .
    env_file: .env
    ports:
      - 8080:8080

volumes:
  pg_data:
    
networks:
  internal: