version: '3.8'

volumes:
  pg_data:

services:
  db:
    image: postgres:13-alpine
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
    ports:
      - 5440:5432
    networks:
      - internal
    volumes:
      - pg_data:/var/lib/postgresql/data

  merch_store:
    build:
      dockerfile: ./scripts/integration_test/Dockerfile
      context: ./../../.
    environment:
      - CONFIG_PATH=./configs/local.yaml
      - SECRET_KEY=12IU3HJ@*&$YDSFDSF&DJS76721G3217
      - POSTGRES_DB=db
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
      - DB_HOST=db
      - DB_PORT=5432
      - DB_SSLMODE=disable
    networks:
      - internal
    ports:
      - 8090:8080

networks:
  internal: